name: 📦 Publish Homebrew Tap

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      # 1. Check out your Homebrew tap repo
      - name: Checkout tap
        uses: actions/checkout@v3
        with:
          repository: uname-n/homebrew-git-action
          path: tap

      # 2. Download the new tarball & compute its SHA256
      - name: Compute release SHA256
        id: sha
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          URL="https://github.com/uname-n/git-action/archive/refs/tags/${TAG}.tar.gz"
          SHA=$(curl -Ls "$URL" | sha256sum | awk '{print $1}')
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "sha256=$SHA" >> $GITHUB_OUTPUT

      # 3. Update the Formula in the tap
      - name: Bump formula
        run: |
          cd tap/Formula
          sed -i "s#^  url \".*\"#  url \"${{ steps.sha.outputs.url }}\"#" git-action.rb
          sed -i "s#^  sha256 \".*\"#  sha256 \"${{ steps.sha.outputs.sha256 }}\"#" git-action.rb

      # 4. Commit & push the bump
      - name: Commit & push
        run: |
          cd tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/git-action.rb
          git commit -m "git-action: bump to ${GITHUB_REF#refs/tags/}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
